services:
  - type: web
    name: kibs-ims-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_migration.py && gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kibs-ims-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://kibs-ims.netlify.app

databases:
  - name: kibs-ims-db
    databaseName: kibs_ims
    user: kibs_admin